#!/bin/bash
while read -r EXAMPLE_DIRECTORY; do
  time env \
    DEBUG="${DEBUG-2}" \
    STACK_INSTANCE_NAME="${STACK_INSTANCE_NAME-blue}" \
    scripts/stackbuild "${EXAMPLE_DIRECTORY}"

  RESULT=$?

  if [ "${RESULT}" != "0" ]; then
    exit 1
  fi
done <<< "$(find examples -mindepth 1 -maxdepth 1)"
