#!/bin/bash
echo "#### AFTER APPLY ####"

echo "Check if the output file exists (TERRAFORM_OUTPUT_JSON_FILE=${TERRAFORM_OUTPUT_JSON_FILE})"

if [ -f "${TERRAFORM_OUTPUT_JSON_FILE}" ]; then
  echo "Output file ${TERRAFORM_OUTPUT_JSON_FILE} contents:"
  cat "${TERRAFORM_OUTPUT_JSON_FILE}"
else
  echo "Output file ${TERRAFORM_OUTPUT_JSON_FILE} does not exist"
fi

echo "Checking jq installation"
jq --version

echo "Retrieving outputs"

ID=$(terraform_output_value "id")
NAME=$(terraform_output_value "name")
COMPOSITE_ID=$(terraform_output_value "composite.id")
COMPOSITE_NONEXISTENT=$(terraform_output_value "composite.nonexistent" "default-value")

cat <<EOF
id......................: ${ID}
name....................: ${NAME}
composite.id............: ${COMPOSITE_ID}
composite.nonexistent...: ${COMPOSITE_NONEXISTENT}
EOF
