#!/bin/sh
generate_azurerm_backend() {
  while read -r LINE; do
    sh -c "echo ${LINE}"
  done < /opt/backend/template.conf
}

generate_gcs_backend() {
cat <<EOF > /opt/src/backend.conf
bucket      = "${GOOGLE_BUCKET}"
prefix      = "$(dirname "${TERRAFORM_REMOTE_STATE_FILE_PATH?}")"
EOF
}

if [ "${TERRAFORM_BACKEND}" == "azurerm" ]; then
  generate_azurerm_backend > /opt/src/backend.conf
fi

if [ "${TERRAFORM_BACKEND}" == "gcs" ]; then
  generate_gcs_backend
fi
