#!/bin/bash
TFP_RUNTIME_SCRIPTS="${TFP_RUNTIME_SCRIPTS-/opt/scripts/tfp/runtime}"

EXECUTION_MOMENT=${1}
EXECUTION_COMMAND=${2}

execution() {
  if [ ${DEBUG-0} -gt 2 ]; then
    echo "tfp:trigger:${EXECUTION_MOMENT}:${EXECUTION_COMMAND}"
  fi

  # Check if the moment is "after" and the command is "apply"
  if [ "${EXECUTION_MOMENT}" = "after" ] && [ "${EXECUTION_COMMAND}" = "apply" ]; then
    terraform_output_save
  fi

  if [ -e "${TFP_RUNTIME_SCRIPTS}" ]; then
    while read SCRIPT_FILE_NAME; do
      . "${SCRIPT_FILE_NAME}"

      EXIT_CODE="$?"

      if [ "${EXIT_CODE-0}" != "0" ]; then
        exit "${EXIT_CODE}"
      fi
    done < <(find "${TFP_RUNTIME_SCRIPTS}" -type f -name "${EXECUTION_MOMENT}-${EXECUTION_COMMAND}*")
  fi
}

if [ "${DEBUG-0}" != "0" ]; then
  execution
else
  execution > /dev/null
fi
