#!/bin/sh
if [ "${DEBUG-0}" -gt 0 ]; then
  echo ""
  echo "Stack Parameters"
  echo ""
  echo "  stack:"
  echo "    name:                   ${STACK_NAME}"
  echo "    version:                ${STACK_VERSION}"
  echo "    instance-name:          ${STACK_INSTANCE_NAME}"
  echo ""
  echo "  terraform:"
  echo "    version:                ${TERRAFORM_VERSION}"
  echo "    provider:               ${TERRAFORM_PROVIDER}"
  echo "    backend:                ${TERRAFORM_BACKEND}"
  echo "    lock-timeout:           ${LOCK_TIMEOUT_SECONDS}"
  echo "    state-file:             ${TERRAFORM_REMOTE_STATE_FILE_PATH}"

  if [ "${DEBUG-0}" -gt 1 ]; then
    echo ""
    /opt/scripts/debug-provider
    /opt/scripts/debug-backend

    echo ""
    echo "Terraform Initialization"
    echo ""
    echo "  provider.tf: |"
    awk '{ print "    " $0 }' < "/opt/src/provider.tf"

    echo ""
    echo "  backend.conf: |"
    awk '{ print "    " $0 }' < "/opt/src/backend.conf"
  fi
fi
