#!/bin/sh

while [[ $# -gt 0 ]]; do
    case "$1" in
        --args)
            argsOption+=" $2"
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

terraform apply \
  -lock-timeout="${LOCK_TIMEOUT_SECONDS?}s" \
  ${argsOption} \
  -auto-approve "${TERRAFORM_PLAN_FILE?}" && \
terraform apply \
  ${argsOption} \
  -auto-approve \
  -refresh-only
