#!/bin/sh

extraArgs="$@"

terraform plan \
  -lock-timeout="${LOCK_TIMEOUT_SECONDS}s" \
  ${extraArgs} \
  -out "${TERRAFORM_PLAN_FILE?}" && \
terraform show \
  -json "${TERRAFORM_PLAN_FILE?}" > "${TERRAFORM_PLAN_JSON_FILE?}"
