#!/bin/sh

while [[ $# -gt 0 ]]; do
    case "$1" in
        --args)
            argsOption+=" $2"
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

terraform plan \
  -lock-timeout="${LOCK_TIMEOUT_SECONDS}s" \
  ${argsOption} \
  -out "${TERRAFORM_PLAN_FILE?}" && \
terraform show \
  -json "${TERRAFORM_PLAN_FILE?}" > "${TERRAFORM_PLAN_JSON_FILE?}"
