#!/bin/sh

TEMP=$(getopt -a -o a: --long args: -- "$@")
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -a|--args) argsOption="${argsOption} $2" ; shift 2 ;;
        --) shift ; break ;;
        *) echo "Internal error!" ; exit 1 ;;
    esac
done

terraform apply \
  -lock-timeout="${LOCK_TIMEOUT_SECONDS?}s" \
  ${argsOption} \
  -auto-approve "${TERRAFORM_PLAN_FILE?}" && \
terraform apply \
  ${argsOption} \
  -auto-approve \
  -refresh-only
