#!/bin/bash

extraArgs="$@"

terraform plan \
  -lock-timeout="${LOCK_TIMEOUT_SECONDS}s" \
  -no-color \
  ${extraArgs} \
  -out "${TERRAFORM_PLAN_FILE?}" | tee "${TERRAFORM_PLAN_TXT_FILE?}"

result=${PIPESTATUS[0]} 

detailed_exit_code_flag=$(echo "${extraArgs}" | grep "detailed-exitcode")

if [ "${detailed_exit_code_flag}" != "" ]; then
  echo "Saving Plan command-result=(${result}) in ${TERRAFORM_OUTPUT_DIRECTORY}/plan_detailed_exitcode"
  echo "${result}" > "${TERRAFORM_OUTPUT_DIRECTORY}/plan_detailed_exitcode"
fi

if [[ "${result}" == "0" || ("${result}" == "2" && "${detailed_exit_code_flag}" != "") ]]; then
  echo "Saving Plan json-file in ${TERRAFORM_PLAN_JSON_FILE}"
  terraform show -json "${TERRAFORM_PLAN_FILE?}" > "${TERRAFORM_PLAN_JSON_FILE?}"
fi

exit ${result} 
