#!/bin/sh
export PATH=/opt/scripts/:${PATH}

initialization() {
  PROVIDER_CREDENTIALS_FILE="/opt/terraform/credentials_provider.conf"
  BACKEND_CREDENTIALS_FILE="/opt/terraform/credentials_backend.conf"

  if [ -e "${PROVIDER_CREDENTIALS_FILE}" ]; then
    # Change backend config from local to specific Provider
    sed -i -e '/  backend/{r /opt/backend/fragment.hcl' -e 'd;}' /opt/src/provider.tf

    # shellcheck disable=SC2039
    # shellcheck disable=SC1090
    source "${PROVIDER_CREDENTIALS_FILE}"
    # shellcheck disable=SC2039
    # shellcheck disable=SC1090
    source "${BACKEND_CREDENTIALS_FILE}"
  fi

  # shellcheck disable=SC1090
  . "/opt/environment_variables.conf"

  TERRAFORM_REMOTE_STATE_FILE_PATH_CUSTOM="$(terraform_remote_state_file_path)"

  if [ -z "${TERRAFORM_REMOTE_STATE_FILE_PATH_CUSTOM}" ]; then
    echo "Please ensure the script 'terraform_remote_state_file_path' return a valid Terraform State File Path."
    exit 1
  fi

  TERRAFORM_REMOTE_STATE_FILE_PATH="stacks/${STACK_NAME?}/${TERRAFORM_REMOTE_STATE_FILE_PATH_CUSTOM?}"

  export TERRAFORM_REMOTE_STATE_FILE_PATH

  generate_backend_configuration_file && \

  show_debug_information && \

  terraform init \
    -reconfigure \
    -upgrade=false \
    -backend-config /opt/src/backend.conf
}

if [ "${DEBUG-0}" != "0" ]; then
  initialization
else
  initialization > /dev/null
fi
