#!/bin/bash

IMAGE_NAME="azure-dummy-stack"
IMAGE_TAG="latest"

az acr login --name wasp.azurecr.io

buildah pull wasp.azurecr.io/${IMAGE_NAME}:${IMAGE_TAG}

# https://github.com/containers/buildah/blob/main/docs/tutorials/01-intro.md
buildah bud \
  --file Dockerfile \
  --rm \
  --layers \
  --tag ${IMAGE_NAME} .

buildah push localhost/terraform-packager:latest "docker://docker.io/silviosilva/${IMAGE_NAME}:${IMAGE_TAG}"

# kaniko
docker run \
  -v "${PWD}:/opt/files/" \
  -v "${HOME}/.docker/config.json:/kaniko/.docker/config.json:ro" \
  gcr.io/kaniko-project/executor:latest \
    --dockerfile=/opt/files/Dockerfile \
    --context=/opt/files/ \
    --destination="docker.io/silviosilva/${IMAGE_NAME}:${IMAGE_TAG}"

KANIKO_IMAGES="${HOME}/.kaniko/images"

docker run \
  -v "${KANIKO_IMAGES}:/opt/images/" \
  -v "${PWD}:/opt/files/" \
  -v "${HOME}/.docker/config.json:/kaniko/.docker/config.json:ro" \
  gcr.io/kaniko-project/executor:latest \
    --dockerfile=/opt/files/Dockerfile \
    --context=/opt/files/ \
    --no-push \
    --destination=${IMAGE_NAME?} \
    --tarPath=/opt/images/${IMAGE_NAME?}.tar

docker load --input "${KANIKO_IMAGES}/${IMAGE_NAME?}.tar"

docker images | grep -E "^REPOSITORY|${IMAGE_NAME?}"
