docker run \
  -v "${LOCAL_TERRAFORM_VARIABLES_DIRECTORY}:/opt/variables/" \
  -v "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}:/opt/output/" \
  -e DEBUG="${DEBUG-0}" \
  -e STACK_INSTANCE_NAME="${STACK_INSTANCE_NAME-default}" \
  -e TF_LOG="${TF_LOG}" \
  -e TF_LOG_PATH="${TF_LOG_PATH}" \
