if [ -z "${CURRENT_USER_ID}" ]; then
  CURRENT_USER_ID=$(id -u)
fi

DOCKER_GROUP_ID=$(getent group docker | cut --delimiter ':' --field 3)

docker run \
  --user "${CURRENT_USER_ID:-1001}:${DOCKER_GROUP_ID:-998}" \
  -v "${LOCAL_TERRAFORM_VARIABLES_DIRECTORY}:/opt/variables/" \
  -v "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}:/opt/output/" \
  -e DEBUG="${DEBUG-0}" \
  -e STACK_INSTANCE_NAME="${STACK_INSTANCE_NAME-default}" \
