#!/bin/bash
source "${TF_PACKAGER_SOURCE_CODE_STACK_CONFIG_FILE?}"

buildah bud \
  --file Dockerfile \
  --rm \
  --layers \
  --tag "${STACK_NAME?}:latest" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}"
