#!/bin/bash
source "${TF_PACKAGER_ENVIRONMENT_VARIABLES_FILE_NAME?}"

"${TF_PACKAGER_SCRIPTS_DIRECTORY}/build_with_${TF_PACKAGER_CONTAINER_BUILDER}"

CODE_EXIT="$?"

if [  "${CODE_EXIT-0}" != "0" ]; then
  exit "${CODE_EXIT}"
fi

FILE_RESULT="${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY}/build_result.txt"

echo "${STACK_NAME?}:${STACK_VERSION}" > "${FILE_RESULT}"

echo "terraform_packager_result_file=${FILE_RESULT}"
