#!/bin/bash
source "${TF_PACKAGER_ENVIRONMENT_VARIABLES_FILE_NAME?}"

TF_PACKAGER_DOCKER_PROGRESS="${TF_PACKAGER_DOCKER_PROGRESS:-auto}" # auto, plain, tty, rawjson

docker build \
  --progress ${TF_PACKAGER_DOCKER_PROGRESS?} \
  --tag "${STACK_NAME?}:latest" \
  --tag "${STACK_NAME?}:${STACK_VERSION}" \
  "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}"

CODE_EXIT="$?"

if [  "${CODE_EXIT-0}" != "0" ]; then
  exit "${CODE_EXIT}"
fi
