#!/bin/bash

# Clear Context Build Directory from previous execution (except plugin_cache_dir)
while read -r LINE; do
  rm -rf "${LINE?}"
done <<< "$(find "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}" -mindepth 1 -not -path '*plugin_cache_dir*')"

# Create Context Build Directories
mkdir -p "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/templates"

# Copy Terraform Source Code to Build Context src/ directory
cp -RL "${TF_SOURCE_CODE_DIRECTORY?}" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/src"

# Copy Credentials to Download Remote Modules on Private Git Repository during the build
cp -R "${HOME}/.ssh" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/.ssh"

# Copy SSH Config File with Strict Host Checking Disabled
cp "${TF_PACKAGER_TEMPLATES_DIRECTORY}/ssh_config" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/.ssh/config"

# Check if Azure Access Token exists
TF_PACKAGER_AZURE_ACCESS_TOKEN_FILE="${TF_PACKAGER_AZURE_ACCESS_TOKEN_FILE-${HOME}/.azure/access_token.json}"
TF_PACKAGER_AZURE_PROFILE_FILE="${TF_PACKAGER_AZURE_PROFILE_FILE-${HOME}/.azure/azureProfile.json}"
TF_PACKAGER_AZURE_MSAL_TOKEN_CACHE_FILE="${TF_PACKAGER_AZURE_MSAL_TOKEN_CACHE_FILE-${HOME}/.azure/msal_token_cache.json}"
mkdir -p "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/.azure"

# If ARM_CLIENT_ID is not set, it means that the authentication assumed is using Azure CLI
if [[ -z "${ARM_CLIENT_ID}" ]]; then
  if [[ -e "${TF_PACKAGER_AZURE_ACCESS_TOKEN_FILE}" ]]; then
    # Retrieves expiration date of the Azure Access Token
    AZURE_ACCESS_TOKEN_EXPIRES_ON_DATE=$(grep "expires_on" ${TF_PACKAGER_AZURE_ACCESS_TOKEN_FILE?} | awk '{ print $2 }' | tr -d ",")

    # Get current timestamp
    CURRENT_SYSTEM_TIMESTAMP=$(date +%s)

    # Check if Azure Access Token has expired
    if [[ ${AZURE_ACCESS_TOKEN_EXPIRES_ON_DATE} -lt ${CURRENT_SYSTEM_TIMESTAMP} ]]; then
      AZURE_ACCESS_TOKEN_EXPIRES_ON_DATE_FORMATED=$(date -d @${AZURE_ACCESS_TOKEN_EXPIRES_ON_DATE} +"%Y-%m-%d %H:%M:%S %:z")
      cat <<EOF
Environment variable ARM_CLIENT_ID is not set but the authentication method using Azure CLI needs to use an Access Token that has expired since: ${AZURE_ACCESS_TOKEN_EXPIRES_ON_DATE_FORMATED}

Please generate a new one and try again:

  az account get-access-token > ${TF_PACKAGER_AZURE_ACCESS_TOKEN_FILE}

EOF
      exit 1
    fi

    cp "${TF_PACKAGER_AZURE_ACCESS_TOKEN_FILE}" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/.azure/access_token.json"
  fi

  if [[ -e "${TF_PACKAGER_AZURE_PROFILE_FILE}" ]]; then
    cp "${TF_PACKAGER_AZURE_PROFILE_FILE}" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/.azure/azureProfile.json"
  fi

  if [[ -e "${TF_PACKAGER_AZURE_MSAL_TOKEN_CACHE_FILE}" ]]; then
    cp "${TF_PACKAGER_AZURE_MSAL_TOKEN_CACHE_FILE}" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/.azure/msal_token_cache.json"
  fi
fi

# Copy Scripts to add into Container Image
cp -R "${TF_PACKAGER_SCRIPTS_DIRECTORY_BUILD}" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/scripts"

if [ -e "${TF_SOURCE_CODE_TFP_SCRIPTS_DIRECTORY}" ]; then
  cp -R "${TF_SOURCE_CODE_TFP_SCRIPTS_DIRECTORY}" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/scripts/tfp"
fi

# Copy Provider Templates
cp -R "${TF_PACKAGER_TEMPLATES_DIRECTORY}/provider" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/templates/provider"

# Copy Backend Templates
cp -R "${TF_PACKAGER_TEMPLATES_DIRECTORY}/backend" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/templates/backend"

# Stack Extensions to Override the Default Behavior
STACK_EXTENSIONS_ROOT_DIRECTORY="${TF_SOURCE_CODE_DIRECTORY}/stack"
STACK_EXTENSIONS_SCRIPTS_DIRECTORY="${STACK_EXTENSIONS_ROOT_DIRECTORY}/scripts"
STACK_EXTENSION_REMOTE_STATE_SCRIPT="${STACK_EXTENSIONS_SCRIPTS_DIRECTORY}/terraform_remote_state_file_path"

if [ -e "${STACK_EXTENSION_REMOTE_STATE_SCRIPT}" ]; then
  echo "Stack Extension Scripts Detected"
  echo ""
  echo "  template:"
  echo "    source:                 ${STACK_EXTENSION_REMOTE_STATE_SCRIPT}"
  echo "    target:                 ${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY}/scripts/"
  echo ""

  cp "${STACK_EXTENSION_REMOTE_STATE_SCRIPT}" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/scripts/"
fi

# Template: Provider Credentials
while read TERRAFORM_PROVIDER_NAME; do
  TERRAFORM_PROVIDER_TEMPLATE_CREDENTIALS_FILE="${TF_PACKAGER_TEMPLATES_DIRECTORY}/provider/${TERRAFORM_PROVIDER_NAME}/credentials_build.conf"
  envsubst < "${TERRAFORM_PROVIDER_TEMPLATE_CREDENTIALS_FILE}" >> "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/credentials_provider.conf"
done <<< "${TERRAFORM_PROVIDER_LIST}"

# Template: Backed Credentials
envsubst < "${TERRAFORM_BACKEND_TEMPLATE_CREDENTIALS_FILE}" > "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/credentials_backend.conf"

# Template: Dockerfile
envsubst < "${TF_PACKAGER_TEMPLATES_DIRECTORY}/Dockerfile" > "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/Dockerfile"

# Template: environment_variables.conf
envsubst < "${TF_PACKAGER_ENVIRONMENT_VARIABLES_FILE_NAME_TEMPLATE}" > "${TF_PACKAGER_ENVIRONMENT_VARIABLES_FILE_NAME}"

# Template: manifest.yaml
envsubst < "${TF_PACKAGER_TEMPLATES_DIRECTORY}/manifest.yaml" > "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}/src/manifest.yaml"
