#!/bin/bash
COMMAND="$@"

if [ "${DEBUG-0}" != "0" ]; then
  echo "${COMMAND?}"
fi

LOCAL_TERRAFORM_VARIABLES_DIRECTORY="${LOCAL_TERRAFORM_VARIABLES_DIRECTORY-${PWD}}"
LOCAL_TERRAFORM_OUTPUT_DIRECTORY="${HOME}/trash/terraform/output"

# Generate empty folder and files to prevent creation as root user
mkdir -p "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}"
touch "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}/terraform.plan"

docker run \
  -v "${LOCAL_TERRAFORM_VARIABLES_DIRECTORY}:/opt/variables/" \
  -v "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}:/opt/output/" \
  -e DEBUG="${DEBUG}" \
  -e STACK_INSTANCE_NAME="${STACK_INSTANCE_NAME-default}" \
  -e GOOGLE_PROJECT="${GOOGLE_PROJECT?}" \
  -e GOOGLE_BUCKET="${GOOGLE_BUCKET?}" \
  -e GOOGLE_PREFIX="${GOOGLE_PREFIX?}" \
  -v "${GOOGLE_CREDENTIALS_FILE?}:/opt/credentials/service-account.json" \
  ${COMMAND?}
