#!/bin/bash
if [ "${TF_PACKAGER_DEBUG_LEVEL-0}" -gt 0 ]; then
  echo ""
  echo "Stack Build"
  echo ""
  echo "  stack:"
  echo "    name:                   ${STACK_NAME?}"
  echo "    version:                ${STACK_VERSION?}"
  echo "    source-code:            ${TF_SOURCE_CODE_DIRECTORY?}"
  echo ""
  echo "  terraform:"
  echo "    version:                ${TERRAFORM_VERSION?}"
  echo "    build-context:          ${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY}"
  echo ""
fi
