#!/bin/bash
echo "ARM_SUBSCRIPTION_ID................: ${ARM_SUBSCRIPTION_ID}"
echo "ARM_TENANT_ID......................: ${ARM_TENANT_ID}"
echo "ARM_CLIENT_ID......................: ${ARM_CLIENT_ID}"
echo "ARM_CLIENT_SECRET..................: ${#ARM_CLIENT_SECRET}"
echo "ARM_STORAGE_ACCOUNT_NAME...........: ${ARM_STORAGE_ACCOUNT_NAME}"
echo "ARM_STORAGE_ACCOUNT_CONTAINER_NAME.: ${ARM_STORAGE_ACCOUNT_CONTAINER_NAME}"
echo "ARM_SAS_TOKEN......................: ${#ARM_SAS_TOKEN}"

if [ -n "${ARM_ACCESS_KEY}" ]; then
  echo "ARM_ACCESS_KEY.....................: ${#ARM_ACCESS_KEY}"
fi
