#!/bin/bash
COMMAND="$@"

if [ "${DEBUG-0}" != "0" ]; then
  echo "${COMMAND?}"
fi

LOCAL_TERRAFORM_VARIABLES_DIRECTORY="${LOCAL_TERRAFORM_VARIABLES_DIRECTORY-${PWD}}"
LOCAL_TERRAFORM_OUTPUT_DIRECTORY="${HOME}/trash/terraform/output"

# Generate empty folder and files to prevent creation as root user
mkdir -p "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}"
touch "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}/terraform.plan"

STACK_RUN_GENERATED_SCRIPT="stackrun-gen.sh"

generate_a_script_to_run_the_command() {
  echo "#!/bin/bash"
  cat templates/run/template-run.conf
  cat templates/run/template-env-var-google.conf
  echo "${COMMAND?}"
}

generate_a_script_to_run_the_command > "${STACK_RUN_GENERATED_SCRIPT}" && \
chmod +x "${STACK_RUN_GENERATED_SCRIPT}" && \
./"${STACK_RUN_GENERATED_SCRIPT}"
