#!/bin/bash
# DEBUG Levels
#   0 - No messages
#   1 - Only Parameters
#   2 - Parameters and Image Builder Outputs
TF_PACKAGER_DEBUG_LEVEL="${DEBUG-2}"

THIS_SCRIPT="${PWD}/${0}"
TF_PROJECT_DIRECTORY="${1}"
TF_SOURCE_CODE_DIRECTORY="${TF_PROJECT_DIRECTORY?}/src"
TF_PACKAGER_SCRIPTS_DIRECTORY="$(dirname "${THIS_SCRIPT}")"
TF_PACKAGER_ROOT_DIRECTORY="${TF_PACKAGER_SCRIPTS_DIRECTORY}/.."
TF_PACKAGER_CONTAINER_BUILDER="${TF_PACKAGER_CONTAINER_BUILDER-docker}"

export PATH="${TF_PACKAGER_SCRIPTS_DIRECTORY}:${PATH}"
export TF_PROJECT_DIRECTORY
export TF_PACKAGER_SCRIPTS_DIRECTORY
export TF_PACKAGER_ROOT_DIRECTORY
export TF_PACKAGER_DEBUG_LEVEL
export TF_SOURCE_CODE_DIRECTORY
export TF_PACKAGER_CONTAINER_BUILDER

if [ -z "${TF_PROJECT_DIRECTORY}" ]; then
  echo ""
  echo "Stack Project Root Folder needs to be informed."
  echo ""
  echo "  Usage:"
  echo ""
  echo "    scripts/stackbuild examples/google-bucket"
  echo ""
  exit 1
fi

validate_source_code "${TF_SOURCE_CODE_DIRECTORY}"

set -euo pipefail

. build_setup_variables "${THIS_SCRIPT}"

show_build_parameters

create_build_context

if [ "${TF_PACKAGER_DEBUG_LEVEL}" -gt 1 ]; then
  build_container_image
else
  build_container_image > /dev/null
fi
