#!/bin/bash
COMMAND="$@"

THIS_SCRIPT="${0}"
THIS_SCRIPT_FOLDER="$(dirname "${THIS_SCRIPT}")"
TEMPLATES_FOLDER="${THIS_SCRIPT_FOLDER}/../templates"

if [ -z "${COMMAND?}" ]; then
  echo "Command not informed."
  exit 1
fi

LOCAL_TERRAFORM_VARIABLES_DIRECTORY="${LOCAL_TERRAFORM_VARIABLES_DIRECTORY-${PWD}}"
LOCAL_TERRAFORM_VARIABLES_DIRECTORY_EXTRA="${LOCAL_TERRAFORM_VARIABLES_DIRECTORY_EXTRA}"

LOCAL_TERRAFORM_OUTPUT_DIRECTORY="${HOME}/trash/terraform/output"

# Generate empty folder and files to prevent creation as root user
mkdir -p "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}"
touch "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}/terraform.plan"
touch "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}/terraform.plan.json"
touch "${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}/terraform.plan.txt"

STACK_RUN_GENERATED_SCRIPT="${HOME}/.stackrun_generated.sh"

DEBUG=${DEBUG-1}

if [ "${DEBUG}" -gt 0 ]; then
  echo ""
  echo "Stack Runner"
  echo ""
  echo "  terraform:"
  echo "    command:                ${COMMAND?}"
  echo "    variables:              ${LOCAL_TERRAFORM_VARIABLES_DIRECTORY?}"
  
  if [ -n "${LOCAL_TERRAFORM_VARIABLES_DIRECTORY_EXTRA}" ]; then
    echo "    variables-extra:        ${LOCAL_TERRAFORM_VARIABLES_DIRECTORY_EXTRA}"
  fi 
  
  echo "    output:                 ${LOCAL_TERRAFORM_OUTPUT_DIRECTORY?}"
fi

export DEBUG

generate_a_script_to_run_the_command() {
  echo "#!/bin/bash"
  echo "LOCAL_TERRAFORM_VARIABLES_DIRECTORY=${LOCAL_TERRAFORM_VARIABLES_DIRECTORY}"
  echo "LOCAL_TERRAFORM_OUTPUT_DIRECTORY=${LOCAL_TERRAFORM_OUTPUT_DIRECTORY}"

  echo ""

  cat "${TEMPLATES_FOLDER?}/stackrun.conf"

  if [ -e "${LOCAL_TERRAFORM_VARIABLES_DIRECTORY_EXTRA}" ]; then
    while read FILE_NAME; do
      BASE_FILE_NAME="$(basename "${FILE_NAME}")"
      COMMAND_VOLUME="$(printf '"%s:/opt/src/%s"' "${FILE_NAME}" "${BASE_FILE_NAME}")"
      echo "  -v ${COMMAND_VOLUME} \\"
    done <<< "$(find ${LOCAL_TERRAFORM_VARIABLES_DIRECTORY_EXTRA} -type f | xargs -n 1)"
  fi

  (
    for CREDENTIALS_FILE in $(find "${TEMPLATES_FOLDER?}/provider" -name credentials_run.conf); do
      cat "${CREDENTIALS_FILE}"
    done

    for CREDENTIALS_FILE in $(find "${TEMPLATES_FOLDER?}/backend" -name credentials_run.conf); do
      cat "${CREDENTIALS_FILE}"
    done
  ) | sort --unique

  echo "${COMMAND?}"
}

generate_a_script_to_run_the_command | uniq > "${STACK_RUN_GENERATED_SCRIPT}"

chmod +x "${STACK_RUN_GENERATED_SCRIPT}"

if [ "${DEBUG}" -gt 1 ]; then
  echo ""
  echo "Stack Runner Command"
  echo ""
  echo "  ${STACK_RUN_GENERATED_SCRIPT}: |"
  awk '{ print "    " $0 }' < "${STACK_RUN_GENERATED_SCRIPT}"
fi

"${STACK_RUN_GENERATED_SCRIPT}"
