#!/bin/bash
source "${TF_PACKAGER_ENVIRONMENT_VARIABLES_FILE_NAME?}"

docker build \
  --rm \
  --tag "${STACK_NAME?}:latest" "${TF_PACKAGER_TEMPORARY_BUILD_CONTEXT_DIRECTORY?}"

docker system prune -f &> /dev/null
